# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00ced773664707c4a1e4d39ed170876ceef02643e20266965089d4cebf9beeacfe307be01d2c5b09ad6a25bde0769d4a6ddeb81fc5f920b93e1b78c5bebbee87

test:
  secret_key_base: 191ea011d5315492fd432cbb748e65e5aa684fbd23a7649e21de89afe8a25326d3f0de26b9b22bb2a43b9678de8b8362e87a456116588de5a3f8ca02ad36c0c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
